### PR TITLE
app icon: Initial app icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
Adds app icon

~~(BTW I noticed that app id is slightly wrong, it should have Halftone starting with capital letter and use `io.github` instead of `com.github`)~~

image

### CODE REVIEW

**Comment by tfuxu** [comment]
Thank you very much! Also, thanks for notifying me about that app ID

**Comment by tfuxu** [comment]
Hmm, I kinda messed up with fixing merge conflicts, as it now shows in PR also changes from my commit, but it should be okay nonetheless.

**Comment by daudix-UFO** [comment]
no problem, I'm still experimenting with the icon, if needed I can open new PR

**Comment by tfuxu** [comment]
@daudix-UFO Do you want to change something in design, or can I merge?

**Comment by daudix-UFO** [comment]
I think it's fine :D

**Comment by tfuxu** [comment]
Great :) LGTM then!

**Pull request merged**
